
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fakescript;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class cup extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public cup() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public cup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public cup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\011\000\002\002\004\000\002\002\004\000\002\057" +
    "\002\000\002\057\004\000\002\057\004\000\002\060\002" +
    "\000\002\060\003\000\002\060\004\000\002\061\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\014\000\010\002\uffff\062\006\063\uffff\001\002\000" +
    "\004\002\016\001\002\000\006\002\ufffc\063\012\001\002" +
    "\000\006\020\007\064\010\001\002\000\006\002\ufffe\063" +
    "\ufffe\001\002\000\006\002\ufffd\063\ufffd\001\002\000\006" +
    "\002\001\063\012\001\002\000\004\017\014\001\002\000" +
    "\006\002\ufffb\063\ufffb\001\002\000\006\002\ufff9\063\ufff9" +
    "\001\002\000\006\002\ufffa\063\ufffa\001\002\000\004\002" +
    "\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\014\000\006\002\003\057\004\001\001\000\002\001" +
    "\001\000\006\060\010\061\012\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\061\014\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$cup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$cup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$cup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$cup$actions {
  private final cup parser;

  /** Constructor */
  CUP$cup$actions(cup parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$cup$do_action_part00000000(
    int                        CUP$cup$act_num,
    java_cup.runtime.lr_parser CUP$cup$parser,
    java.util.Stack            CUP$cup$stack,
    int                        CUP$cup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$cup$result;

      /* select the action based on the action number */
      switch (CUP$cup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= package_head include_head 
            {
              Object RESULT =null;

              CUP$cup$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$cup$stack.elementAt(CUP$cup$top-1)), ((java_cup.runtime.Symbol)CUP$cup$stack.peek()), RESULT);
            }
          return CUP$cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$cup$stack.elementAt(CUP$cup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$cup$stack.elementAt(CUP$cup$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$cup$stack.elementAt(CUP$cup$top-1)).value;
		RESULT = start_val;
              CUP$cup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$cup$stack.elementAt(CUP$cup$top-1)), ((java_cup.runtime.Symbol)CUP$cup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$cup$parser.done_parsing();
          return CUP$cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // package_head ::= 
            {
              Object RESULT =null;
		
	
              CUP$cup$result = parser.getSymbolFactory().newSymbol("package_head",45, ((java_cup.runtime.Symbol)CUP$cup$stack.peek()), RESULT);
            }
          return CUP$cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // package_head ::= PACKAGE IDENTIFIER 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$cup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$cup$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$cup$stack.peek()).value;
		
		System.out.print(e);
		//FKLOG("[bison]: package %s", $2.c_str());
		//myflexer *l = (myflexer *)parm;
		//l->set_package($2.c_str());
	
              CUP$cup$result = parser.getSymbolFactory().newSymbol("package_head",45, ((java_cup.runtime.Symbol)CUP$cup$stack.elementAt(CUP$cup$top-1)), ((java_cup.runtime.Symbol)CUP$cup$stack.peek()), RESULT);
            }
          return CUP$cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // package_head ::= PACKAGE IDENTIFIER_DOT 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$cup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$cup$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$cup$stack.peek()).value;
		
		System.out.print(e);
		//FKLOG("[bison]: package %s", $2.c_str());
		//myflexer *l = (myflexer *)parm;
		//l->set_package($2.c_str());
	
              CUP$cup$result = parser.getSymbolFactory().newSymbol("package_head",45, ((java_cup.runtime.Symbol)CUP$cup$stack.elementAt(CUP$cup$top-1)), ((java_cup.runtime.Symbol)CUP$cup$stack.peek()), RESULT);
            }
          return CUP$cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // include_head ::= 
            {
              Object RESULT =null;
		
	
              CUP$cup$result = parser.getSymbolFactory().newSymbol("include_head",46, ((java_cup.runtime.Symbol)CUP$cup$stack.peek()), RESULT);
            }
          return CUP$cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // include_head ::= include_define 
            {
              Object RESULT =null;

              CUP$cup$result = parser.getSymbolFactory().newSymbol("include_head",46, ((java_cup.runtime.Symbol)CUP$cup$stack.peek()), ((java_cup.runtime.Symbol)CUP$cup$stack.peek()), RESULT);
            }
          return CUP$cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // include_head ::= include_head include_define 
            {
              Object RESULT =null;

              CUP$cup$result = parser.getSymbolFactory().newSymbol("include_head",46, ((java_cup.runtime.Symbol)CUP$cup$stack.elementAt(CUP$cup$top-1)), ((java_cup.runtime.Symbol)CUP$cup$stack.peek()), RESULT);
            }
          return CUP$cup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // include_define ::= INCLUDE STRING_DEFINITION 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$cup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$cup$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$cup$stack.peek()).value;
		
		System.out.print(e);
		//FKLOG("[bison]: include %s", $2.c_str());
		//myflexer *l = (myflexer *)parm;
		//l->add_include($2.c_str());
	
              CUP$cup$result = parser.getSymbolFactory().newSymbol("include_define",47, ((java_cup.runtime.Symbol)CUP$cup$stack.elementAt(CUP$cup$top-1)), ((java_cup.runtime.Symbol)CUP$cup$stack.peek()), RESULT);
            }
          return CUP$cup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$cup$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$cup$do_action(
    int                        CUP$cup$act_num,
    java_cup.runtime.lr_parser CUP$cup$parser,
    java.util.Stack            CUP$cup$stack,
    int                        CUP$cup$top)
    throws java.lang.Exception
    {
              return CUP$cup$do_action_part00000000(
                               CUP$cup$act_num,
                               CUP$cup$parser,
                               CUP$cup$stack,
                               CUP$cup$top);
    }
}

}
