
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package fakescript;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FAKE = 43;
  public static final int FFALSE = 8;
  public static final int DIVIDE = 21;
  public static final int CLOSE_BIG_BRACKET = 66;
  public static final int MORE_OR_EQUAL = 26;
  public static final int NEW_ASSIGN = 61;
  public static final int FKUUID = 44;
  public static final int YIELD = 56;
  public static final int SLEEP = 57;
  public static final int PLUS_ASSIGN = 35;
  public static final int MULTIPLY_ASSIGN = 38;
  public static final int CASE = 59;
  public static final int NOT_EQUAL = 29;
  public static final int CONTINUE = 55;
  public static final int FCONST = 47;
  public static final int IDENTIFIER_POINTER = 51;
  public static final int FOR = 41;
  public static final int LESS = 25;
  public static final int MINUS = 20;
  public static final int NOT = 54;
  public static final int IS = 53;
  public static final int AND = 32;
  public static final int ELSEIF = 62;
  public static final int CLOSE_SQUARE_BRACKET = 46;
  public static final int LESS_OR_EQUAL = 27;
  public static final int OR = 33;
  public static final int VAR_BEGIN = 2;
  public static final int FTRUE = 7;
  public static final int ARG_SPLITTER = 18;
  public static final int INC = 42;
  public static final int PLUS = 19;
  public static final int MULTIPLY = 22;
  public static final int ASSIGN = 23;
  public static final int IF = 9;
  public static final int EOF = 0;
  public static final int RETURN = 3;
  public static final int EQUAL = 28;
  public static final int error = 1;
  public static final int INCLUDE = 49;
  public static final int OPEN_SQUARE_BRACKET = 45;
  public static final int DIVIDE_MOD_ASSIGN = 39;
  public static final int STRING_CAT = 64;
  public static final int NUMBER = 15;
  public static final int CLOSE_BRACKET = 31;
  public static final int BREAK = 4;
  public static final int OPEN_BRACKET = 30;
  public static final int SWITCH = 58;
  public static final int FKFLOAT = 34;
  public static final int COLON = 40;
  public static final int ELSE = 11;
  public static final int FUNC = 5;
  public static final int PACKAGE = 48;
  public static final int WHILE = 6;
  public static final int DIVIDE_ASSIGN = 37;
  public static final int DEFAULT = 60;
  public static final int THEN = 10;
  public static final int OPEN_BIG_BRACKET = 65;
  public static final int STRING_DEFINITION = 13;
  public static final int END = 12;
  public static final int RIGHT_POINTER = 63;
  public static final int STRUCT = 52;
  public static final int DIVIDE_MOD = 17;
  public static final int MINUS_ASSIGN = 36;
  public static final int MORE = 24;
  public static final int IDENTIFIER_DOT = 50;
  public static final int IDENTIFIER = 14;
  public static final int SINGLE_LINE_COMMENT = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR_BEGIN",
  "RETURN",
  "BREAK",
  "FUNC",
  "WHILE",
  "FTRUE",
  "FFALSE",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "STRING_DEFINITION",
  "IDENTIFIER",
  "NUMBER",
  "SINGLE_LINE_COMMENT",
  "DIVIDE_MOD",
  "ARG_SPLITTER",
  "PLUS",
  "MINUS",
  "DIVIDE",
  "MULTIPLY",
  "ASSIGN",
  "MORE",
  "LESS",
  "MORE_OR_EQUAL",
  "LESS_OR_EQUAL",
  "EQUAL",
  "NOT_EQUAL",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "AND",
  "OR",
  "FKFLOAT",
  "PLUS_ASSIGN",
  "MINUS_ASSIGN",
  "DIVIDE_ASSIGN",
  "MULTIPLY_ASSIGN",
  "DIVIDE_MOD_ASSIGN",
  "COLON",
  "FOR",
  "INC",
  "FAKE",
  "FKUUID",
  "OPEN_SQUARE_BRACKET",
  "CLOSE_SQUARE_BRACKET",
  "FCONST",
  "PACKAGE",
  "INCLUDE",
  "IDENTIFIER_DOT",
  "IDENTIFIER_POINTER",
  "STRUCT",
  "IS",
  "NOT",
  "CONTINUE",
  "YIELD",
  "SLEEP",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "NEW_ASSIGN",
  "ELSEIF",
  "RIGHT_POINTER",
  "STRING_CAT",
  "OPEN_BIG_BRACKET",
  "CLOSE_BIG_BRACKET"
  };
}

